project:
  type: website
  output-dir: docs

website:
  title: "Kaisa Nilsson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mp1.qmd
        text: Mini-Project 1
      - mp3.qmd

format:
  html:
    code-fold: true
    theme: styles.scss
    mainfont: 'Nunito Sans'
    toc: true



